apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: gitops
spec:
  entryPoints:
  - websecure
  - ssh
  routes:
  - kind: Rule
    # NOTE, the domain name resolution bellow is more for example, it require re-implementation ater
    match: HostRegexp(`{app:(git|gitea)}.{{ context.gitea.config.server.DOMAIN.split('.', 1)[1] }}`) #&& Headers(`Content-Type`, `application/http`)
    priority: 10
    services:
    - name: gitea-http
      port: 3000
      namespace: gitops
  - kind: Rule
    match: HostRegexp(`{app:(git)}.{{ context.gitea.config.server.DOMAIN.split('.', 1)[1] }})
    priority: 11
    services:
    - name: gitea-ssh
      port: 30022
      scheme: UDP
      namespace: gitops
  tls:
    certResolver: cloudflare
    domains:
    - main: {{ context.gitea.config.server.DOMAIN.split('.', 1)[1] }}
      sans:
      - git.{{ context.gitea.config.server.DOMAIN.split('.', 1)[1] }}
      - gitea.{{ context.gitea.config.server.DOMAIN.split('.', 1)[1] }}

  # doc https://www.reddit.com/r/Traefik/comments/lpkexu/traefi_v2_and_gitea_ssh_access_again/
