apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: &nm jellyfin
  namespace: &ns jellyfin
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`jellyfin.{{ args.domain }})
    priority: 10
    services:
    - name: jellyfin-main
      port: 8384
      namespace: *ns
    - name: jellyfin-listen
      port: 22000
      namespace: *ns
    - name: jellyfin-discovery
      port: 21027
      namespace: *ns
tls:
  domains:
  - main: {{ args.domain }}
    sans:
    - jellyfin.{{ args.domain }}
