{
 "title": "Gitlab runner",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "search", "label": "Search" },
   { "name": "namespace", "query": "gitlab" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Concurrency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gitlab_runner_concurrent)  ",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Runner nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_spec_unschedulable{node!~\".*pool-static.*\"} == 0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_memory_bytes)" }
   ]
  },
  {
   "title": "Core count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Max memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace!=\"\"})"
    }
   ]
  },
  {
   "title": "Concurrency per node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gitlab_runner_concurrent) / count(kube_node_spec_unschedulable{node!~\".*pool-static.*\"} == 0)"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Running jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (state) (gitlab_runner_jobs)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Failed jobs [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (failure_reason) (increase(gitlab_runner_failed_jobs_total[15m]) / ignoring(failure_reason) group_left increase(gitlab_runner_jobs_total[15m]))",
     "legendFormat": "{{ failure_reason }}"
    }
   ]
  },
  {
   "title": "Jobs finished delta 10m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_runner_jobs_total[10m]))"
    }
   ]
  },
  {
   "title": "Failed job rate [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (failure_reason) (increase(gitlab_runner_failed_jobs_total[10m]))",
     "legendFormat": "{{ failure_reason }}"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Counter tracking exceeding of request concurrency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(gitlab_runner_request_concurrency_exceeded_total[2m])",
       "legendFormat": "{{ runner}} "
      },
      { "expr": "gitlab_runner_concurrent", "legendFormat": "Concurrent limit" }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Log rate by level",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"gitlab\",container=\"gitlab-runner\"} |~ \"$search\"[$__interval])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Runner logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{container=\"gitlab-runner\",namespace=\"gitlab\"} |~ \"$search\""
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Pod states in $namespace namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"gitlab\",phase!=\"Succeeded\"} == 1)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "CPU usage by namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) / ignoring(namespace) group_left sum(instance:node_num_cpu:sum)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory usage (w/o cache) by namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_working_set_bytes{namespace!=\"\"}) / ignoring(namespace) group_left sum(:node_memory_MemAvailable_bytes:sum)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Container with high memory usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{namespace!=\"\"} > 4e9)"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of api requests",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "count" }
     ],
     "targets": [
      {
       "expr": "delta(gitlab_runner_api_request_statuses_total[2m])",
       "legendFormat": "{{app}} : {{endpoint}} : {{status}}"
      }
     ]
    },
    {
     "title": "The number of caught errors",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "count" }
     ],
     "targets": [
      {
       "expr": "delta(gitlab_runner_errors_total[2m])",
       "legendFormat": "{{app}} : {{level}}"
      }
     ]
    }
   ]
  }
 ]
}