{% if context.l2advertisement is defined %}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: metallb
spec:
  ipAddressPools: {{context.l2advertisement}}
{%- endif %}

{% for key,value in context.ipaddresspool.items() %}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{key}}
  namespace: metallb
spec:
  addresses: {{value}}
{%- endfor %}
