{% if context.l2advertisement is defined %}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: metallb
spec:
  ipAddressPools: {{context.l2advertisement}}
{%- endif %}

{% for key,value in context.ipaddresspool.items() %}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{key}}
  namespace: metallb
spec:
  addresses: {{value}}
#---
# apiVersion: metallb.io/v1beta2
# kind: BGPPeer
# metadata:
#   name: torouter
#   namespace: metallb
# spec:
#   myASN: 64512
#   peerASN: 65530
#   peerAddress: 172.31.1.1
# ---
# apiVersion: metallb.io/v1beta1
# kind: BGPAdvertisement
# metadata:
#   name: local
#   namespace: metallb
# spec:
#   ipAddressPools:
#   - {{key}}
#   aggregationLength: 32
#   # localPref: 100
#   # communities:
#   # - 65535:65282
{%- endfor %}
