# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2

# vars context, merge with defaults
{{ context | to_yaml }}

# best practice defaults
common:
  image:
    repository: homeassistant/home-assistant
    tag: 2024.1 # 2023.12.4

  env:
    TZ: UTC

  persistence:
    config:
      enabled: true
      size: 5Gi

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet



  probes:
    liveness:
      enabled: true
    readiness:
      enabled: true
    startup:
      enabled: false


  service:
    main:
      #annotations:
      #  metallb.universe.tf/allow-shared-ip: 'true'
      ports:
        http:
          port: 8123
  # FIXME, cleanup section, conditional
  ingress:
    main:
      enabled: true
      #ingressClassName: traefik
      annotations:
        ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: home-assistant
        hajimari.io/group: network
        hajimari.io/appName: hass
      hosts:
      - host: hass.{{ args.domain }}
        paths:
        - path: /
          pathType: Prefix
      - host: hass.{{ args.domain }}
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - hass.{{ args.domain }}

  resources:
    requests:
      cpu: 100m
      memory: 512M
    limits:
      memory: 2048M


