# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2
# file is only used when foler/git included as kluctl.io sub-deployment
# order and noOverride is intentional, passed Vars must take precendece

deployments:
- path: ../thanos
  vars:
  # env specific setup (prod|test|ci)
  - file: vars-{{ args.env }}.yml
    ignoreMissing: true
    noOverride: true
  # best practice defaults
  - file: vars.yml
    ignoreMissing: true
    noOverride: true
