# vim: ft=yaml.jinja2 syntax=yaml sts=2 ts=2 sw=2

helmChart:
  # renovate: registryUrl=https://grafana.github.io/helm-charts
  repo: https://grafana.github.io/helm-charts
  chartName: grafana
  chartVersion: 7.2.5
  releaseName: "grafana"
  namespace: mon
  skipCRDs: False
  skipPrePull: True
  #skipUpdate: False

kustomize:
  namespace: mon
  labels:
  - includeSelectors: true
    pairs:
      app: grafana
      env: {{ target.name }}

  # configurations:
  # - {compose}}/kustomizeConfig.yaml
  resources:
  - helm-rendered.yaml
  generatorOptions:
    disableNameSuffixHash: true
  commonAnnotations:
    "prometheus.io/scrape": "true"
    #"prometheus.io/scheme": http

  secretGenerator:
  - name: grafana-oauth-secret
    literals:
    - client_id=admin
    - client_secret={{ secrets.grafana.admin_password }}
  # - name: grafana-auth0-secret
  #   literals:
  #   - client_id={{ secrets.grafana.auth0.client_id }}
  #   - client_secret={{ secrets.grafana.auth0.client_secret }}



context:
  tolerations:
  - key: "arm"
    operator: "Exists"

  deploymentStrategy:
    type: Recreate

  podAnnotations:
    #backup.velero.io/backup-volumes: storage
    configmap.reloader.stakater.com/reload: "grafana"

  persistence:
    enabled: true
    storageClassName: "longhorn"
    size: 10Gi
    accessModes:
    - ReadWriteOnce

  env:
    GF_ANALYTICS_CHECK_FOR_UPDATES: false
    GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
    GF_EXPLORE_ENABLED: true
    GF_GRAFANA_NET_URL: https://grafana.net
    GF_LOG_FILTERS: rendering:debug
    GF_LOG_MODE: console
    GF_PANELS_DISABLE_SANITIZE_HTML: true
    GF_SECURITY_ALLOW_EMBEDDING: true
    GF_SERVER_ROOT_URL: https://grafana.apealive.net
    #GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "natel-discrete-panel,pr0ps-trackmap-panel,panodata-map-panel"
    #VAR_BLOCKY_URL: "http://blocky.default.svc.cluster.local:4000"
  # envFromSecrets:
  #   - name: grafana-auth0-secret

  plugins:
  - pr0ps-trackmap-panel
  - natel-plotly-panel
  - grafana-clock-panel
  - vonage-status-panel
  - grafana-piechart-panel
  - https://github.com/panodata/panodata-map-panel/releases/download/0.16.0/panodata-map-panel-0.16.0.zip;grafana-worldmap-panel-ng
  - grafana-clock-panel
  - grafana-worldmap-panel
  - natel-discrete-panel



  serviceMonitor:
    enabled: true
  serviceAccount:
    autoMount: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      1-node-exporter:
        url: https://grafana.com/api/dashboards/11074/revisions/9/download
        datasource: Prometheus
      #blocky:
      #  url: https://raw.githubusercontent.com/0xERR0R/blocky/v0.18/docs/blocky-grafana.json
      #  datasource: Prometheus
      # Ref: https://grafana.com/grafana/dashboards/2842
      #flux-cluster:
      #  url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
      #  datasource: Prometheus
      #flux-control-plane:
      #  url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
      #  datasource: Prometheus
      #frigate:
      #  url: https://raw.githubusercontent.com/epcim/gitops-infra/master/monitoring/grafana/dashboards/frigate.json
      #  datasource: Prometheus
      #home-assistant:
      #  #FIXME url: https://raw.githubusercontent.com/epcim/gitops-infra/master/monitoring/grafana/dashboards/home_assistant.json
      #  url: https://raw.githubusercontent.com/billimek/k8s-gitops/master/monitoring/grafana/dashboards/home_assistant.json
      #  datasource: home_assistant
      loki:
        gnetId: 13407
        revision: 1
        datasource: Prometheus
      #minio-overview:
      #  url: https://raw.githubusercontent.com/epcim/gitops-infra/master/monitoring/grafana/dashboards/minio_overview.json
      #  datasource: Prometheus
      #nginx-dashboard:
      #  url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
      #  datasource: Prometheus
      node-exporter-full:
        gnetId: 1860
        revision: 23
        datasource: Prometheus
      #speedtest-exporter:
      #  url: https://raw.githubusercontent.com/epcim/gitops-infra/master/monitoring/grafana/dashboards/speedtest-exporter.json
      #  datasource: Prometheus
      #TrueNAS:
      #  url: https://grafana.com/api/dashboards/12921/revisions/1/download
      #  datasource: TrueNAS
      # Ref: https://grafana.com/grafana/dashboards/11315
      unifi-client-insights:
        gnetId: 11315
        revision: 8
        datasource: Prometheus
      # Ref: https://grafana.com/grafana/dashboards/11311
      unifi-network-sites:
        gnetId: 11311
        revision: 4
        datasource: Prometheus
      # Ref: https://grafana.com/grafana/dashboards/11314
      unifi-uap-insights:
        gnetId: 11314
        revision: 9
        datasource: Prometheus
      # Ref: https://grafana.com/grafana/dashboards/11312
      unifi-usw-insights:
        gnetId: 11312
        revision: 8
        datasource: Prometheus
      #ups:
      #  url: https://raw.githubusercontent.com/epcim/gitops-infra/master/monitoring/grafana/dashboards/ups.json
      #  datasource: Prometheus
      #uptimerobot:
      #  url: https://raw.githubusercontent.com/lekpamartin/uptimerobot_exporter/master/dashboards/grafana.json
      #  datasource: Prometheus
      #velero:
      #  url: https://grafana.com/api/dashboards/11055/revisions/2/download
      #  datasource: Prometheus
      #windows-node:
      #  url: https://raw.githubusercontent.com/epcim/gitops-infra/master/monitoring/grafana/dashboards/windows_node.json
      #  datasource: Prometheus
      falco:
        url: https://github.com/falcosecurity/falco-exporter/raw/master/grafana/dashboard.json
        datasource: Prometheus
      loki-dashboard-quick-search:
        gnetId: 12019
        revision: 2
        datasource:
        - name: Prometheus
        - name: Loki
      prometheus-exporter-summary:
        #FIXME url: https://raw.githubusercontent.com/epcim/gitops-infra/master/monitoring/grafana/dashboards/prometheus_exporter_summary.json
        url: https://raw.githubusercontent.com/billimek/k8s-gitops/master/monitoring/grafana/dashboards/prometheus_exporter_summary.json
        datasource: Prometheus
      speedtest-exporter:
        url: https://raw.githubusercontent.com/billimek/k8s-gitops/master/monitoring/grafana/dashboards/speedtest-exporter.json
        datasource: Prometheus
      ups:
        url: https://raw.githubusercontent.com/billimek/k8s-gitops/master/monitoring/grafana/dashboards/ups.json
        datasource: Prometheus
  sidecar:
    datasources:
      enabled: true
      searchNamespace: ALL
      # defaultDatasourceEnabled: false
    dashboards:
      enabled: true
      searchNamespace: ALL

  {% if args.bootstrap %}
  admin:
    existingSecret: grafana
  {% endif %}

  # extraSecretMounts:
  # - extraSecretMounts:
  #   - name: auth-generic-oauth-secret-mount
  #     secretName: auth-generic-oauth-secret
  #     defaultMode: 0440
  #     mountPath: /etc/secrets/auth_generic_oauth
  #     readOnly: true

  # vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2
