apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin
    namespace: gitops
    annotations:
        kustomize.config.k8s.io/behavior: replace
        sealedsecrets.bitnami.com/managed: "true"
type: Opaque
stringData:
    username: gitea_admin
    password: {{ secrets.gitea.admin_password }}
    email: {{ secrets.gitea.admin_email }}
